spring.application.name=LoanPricingApprovalApplication
# ===============================
# Server configuration
# ===============================
server.port=8081

# ===============================
# MongoDB configuration
# - For local MongoDB: localhost:27017
# - Change uri if you use Docker/Atlas
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/loan_db

# ===============================
# JWT configuration
# ===============================
app.jwt.secret=very-strong-secret-change-in-prod-1234567890

# JWT expiration time in milliseconds (1 hour)
app.jwt.expiration-ms=3600000


# ===============================
# Jackson / JSON config
# ===============================
spring.jackson.serialization.write-dates-as-timestamps=false

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.com.bank.loan=DEBUG
